# Generated by Django 5.0 on 2023-12-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauda', '0002_sauda_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauda',
            name='broker_name',
            field=models.ForeignKey(help_text='select broker u want to sell', on_delete=django.db.models.deletion.RESTRICT, to='sauda.broker'),
        ),
    ]
